// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: G.Gobang.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GGobangRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GGobangRoot : GPBRootObject
@end

#pragma mark - GobangData

typedef GPB_ENUM(GobangData_FieldNumber) {
  GobangData_FieldNumber_Type = 1,
  GobangData_FieldNumber_Subtype = 2,
  GobangData_FieldNumber_RoomId = 3,
  GobangData_FieldNumber_From = 4,
  GobangData_FieldNumber_To = 5,
  GobangData_FieldNumber_X = 6,
  GobangData_FieldNumber_Y = 7,
  GobangData_FieldNumber_Msg = 8,
};

@interface GobangData : GPBMessage

/** 信息类型  1进入房间，2离开房间，3准备,4开始，5悔棋，6同意悔棋,100下棋 */
@property(nonatomic, readwrite) uint32_t type;

/**  1.黑子  2.白子 */
@property(nonatomic, readwrite) uint32_t subtype;

/** 房间id */
@property(nonatomic, readwrite) uint32_t roomId;

/** 消息发送方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

/** 消息接受方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/** 棋盘 x轴 */
@property(nonatomic, readwrite) uint32_t x;

/** 棋盘 y轴 */
@property(nonatomic, readwrite) uint32_t y;

/** 消息接受方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@end

#pragma mark - GobangAck

typedef GPB_ENUM(GobangAck_FieldNumber) {
  GobangAck_FieldNumber_ErrCode = 1,
  GobangAck_FieldNumber_ErrMsg = 2,
};

@interface GobangAck : GPBMessage

/** 0:发送成功，msg_id有效；1+：发送失败; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *errCode;

/** 错误消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
