// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Audio.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImAudioRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImAudioRoot : GPBRootObject
@end

#pragma mark - IMAudioData

typedef GPB_ENUM(IMAudioData_FieldNumber) {
  IMAudioData_FieldNumber_Type = 1,
  IMAudioData_FieldNumber_RoomId = 2,
  IMAudioData_FieldNumber_From = 3,
  IMAudioData_FieldNumber_To = 4,
  IMAudioData_FieldNumber_Msg = 5,
  IMAudioData_FieldNumber_AudioData = 6,
};

@interface IMAudioData : GPBMessage

/** 信息类型  1请求语音通话，2同意语音通话，3挂断语音通话 */
@property(nonatomic, readwrite) uint32_t type;

/** 房间id */
@property(nonatomic, readwrite) uint32_t roomId;

/** 消息发送方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

/** 消息接受方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

/** 消息接受方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

/** 语音data */
@property(nonatomic, readwrite, copy, null_resettable) NSData *audioData;

@end

#pragma mark - IMAudioAck

typedef GPB_ENUM(IMAudioAck_FieldNumber) {
  IMAudioAck_FieldNumber_ErrCode = 1,
  IMAudioAck_FieldNumber_ErrMsg = 2,
};

@interface IMAudioAck : GPBMessage

/** 0:发送成功，msg_id有效；1+：发送失败; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *errCode;

/** 错误消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
